"""empty message

Revision ID: f8d9af20d7dc
Revises: 80c603b1b0e1
Create Date: 2022-08-05 15:37:03.340981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d9af20d7dc'
down_revision = '80c603b1b0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_flask', sa.Column('session_user', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_flask', 'session_user')
    # ### end Alembic commands ###
