"""empty message

Revision ID: f90b9ee6520b
Revises: 6386be665b9c
Create Date: 2022-08-09 08:02:00.389971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90b9ee6520b'
down_revision = '6386be665b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_flask', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_flask', 'password_hash')
    # ### end Alembic commands ###
